os:
  - linux

language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "12"
deploy:
  provider: script
  script: yarn install && yarn travisdeploy
  skip_cleanup: true
  on:
    branch: master
